version: '3'
services:
  minio:
    image: minio/minio:${SOFTWARE_VERSION_TAG}
    restart: always
    dns:
      - 8.8.8.8
    ports:
      - "172.17.0.1:9000:9000"
      - "172.17.0.1:9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${ADMIN_LOGIN}
      MINIO_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://[CI_CD_DOMAIN]
      MINIO_SERVER_URL: https://[CI_CD_DOMAIN]:34256 
    command: server --address ":9000" --console-address ":9001" /data
